### ISSUE TITLE
Add uri getter to Fluri class

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/fluri#28]
```dart
// if you need to interface with another API that uses Uri...
Fluri fluri = new Fluri();
fluri.toUri();
```

@trentgrover-wf @maxwellpeterson-wf thoughts?

**Comment by trentgrover-wf** [comment]
isn't there already a getter for the underlying Uri?

**Comment by evanweible-wf** [comment]
There is for the `FluriMixin` class, but not for the standalone `Fluri` class. I thought it would be weird, especially if you still named fluri instances `uri`:

```dart
Fluri uri = new Fluri();
uri.uri; // <-- weird
```

Maybe I should avoid advocating naming fluri instances `uri` in the examples to avoid that

**Comment by maxwellpeterson-wf** [comment]
Does the Uri instance already exist or will it need to be created when the user wants access to it?

**Comment by evanweible-wf** [comment]
already exists

**Comment by maxwellpeterson-wf** [comment]
In that case I sort of prefer the getter `.uri`... 
¯\_(ツ)_/¯

**Comment by trentgrover-wf** [comment]
I'd vote to just use the getter and change up the docs to use `fluri` as the standard name instead of `uri`:
```
Fluri fluri = new Fluri();
fluri.uri;
```

**Comment by evanweible-wf** [comment]
:+1:

**Comment by evanweible-wf** [comment]
Well, I was wrong :smile:. Both the `Fluri` and `FluriMixin` classes have the `uri` getter. So I'll just update the docs
