### ISSUE TITLE
AddPathSegment, SetQueryParam

### ISSUE THREAD

**Issue by oliverjanik** [Workiva/fluri#39]
I think these would cover a lot of use-cases where you have a baseUrl for an Api and you need to add segments and/or set query params.

**Comment by evanweible-wf** [comment]
@oliverjanik thanks for the suggestion! I like the idea, I'll look into adding these soon.

**Comment by evanweible-wf** [comment]
Added in #40 and released to pub: https://pub.dartlang.org/packages/fluri

@oliverjanik
